<?php
return array (
  21 => 
  array (
    'posid' => '21',
    'modelid' => '12',
    'catid' => '0',
    'name' => '首页新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '26',
    'catid' => '0',
    'name' => '顶部产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '4',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '25',
    'catid' => '0',
    'name' => '首页新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '4',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '18',
    'catid' => '0',
    'name' => '首页产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '18',
    'catid' => '0',
    'name' => '顶部产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '17',
    'catid' => '0',
    'name' => '首页新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '13',
    'catid' => '0',
    'name' => '顶部产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '22',
    'catid' => '0',
    'name' => '首页产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '22',
    'catid' => '0',
    'name' => '顶部产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '21',
    'catid' => '0',
    'name' => '首页新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '26',
    'catid' => '0',
    'name' => '首页产品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '4',
    'thumb' => '',
  ),
);
?>